version: "3"

services:
  poputchiki-db:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=a10bbb
      - POSTGRES_DB=poputchiki
      - PG_DATA=/var/poputchiki/postgresql/data
    volumes:
      - postgresql:/var/poputchiki/postgresql
      - postgresql_data:/var/poputchiki/postgresql/data
    restart: always
    networks:
      - poputchiki-net
  poputchiki-service:
    image: abugaeva/poputchiki-app:1.0
    ports:
      - 8081:8081
    environment:
      - POSTGRES_PATH=jdbc:postgresql://poputchiki-db:5432/poputchiki
      - POSTGRES_PASSWORD=a10bbb
      - POSTGRES_USERNAME=postgres
    depends_on:
      - poputchiki-db
    restart: always
    networks:
      - poputchiki-net

  poputchiki-service-frontend:
    image: abugaeva/poputchiki-app-front
    ports:
      - 80:80
    networks:
      - poputchiki-net

volumes:
  postgresql:
  postgresql_data:
    driver: local

networks:
  poputchiki-net:
    driver:
       bridge
